import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { OverviewState } from './overview-state.service';
import { UiIconComponent } from '../../shared/ui-icon.component';
@Component({
  selector: 'app-daily-schedule', imports: [UiIconComponent],
  template: `<section class="panel" aria-labelledby="schedule-heading"><div class="card-top"><div><div class="kicker">A GENTLE RHYTHM</div><h2 id="schedule-heading">Your daily ritual</h2></div><span class="icon-tile"><app-ui-icon name="clock" /></span></div><div class="timeline" data-testid="daily-schedule">@for (slot of state.schedule(); track slot.timestamp) {
    <div class="timeline-slot" [class.next]="slot.next"><div class="time"><time [attr.datetime]="slot.timestamp">{{ slot.time }}</time><span class="timeline-dot"></span></div><div class="slot-copy"><strong>{{ slot.title }}</strong><p class="muted">{{ slot.detail }}</p></div>@if (slot.next) { <span class="pill">Up next</span> }</div>
  } @empty { <p class="empty-note">Your water breaks will appear here when your desktop routine is available.</p> }</div><p class="muted schedule-note">A little space for yourself, throughout the day.</p></section>`,
  styleUrl: './overview-card.scss', styles: ['.card-top h2 { margin-top: 7px; }.timeline-slot { display: flex; align-items: flex-start; gap: 19px; position: relative; padding: 9px 0 16px; }.time { display: flex; align-items: center; justify-content: space-between; gap: 18px; min-width: 93px; color: var(--muted); font-size: 11px; padding-top: 2px; font-variant-numeric: tabular-nums; }.timeline-dot { width: 7px; height: 7px; background: var(--slingsip-text-muted); border-radius: 50%; flex-shrink: 0; position: relative; }.timeline-slot:not(:last-child) .timeline-dot::after { content: ""; position: absolute; width: 1px; height: 49px; left: 3px; top: 10px; background: var(--slingsip-border-accent); }.next .timeline-dot { background: var(--mint); box-shadow: 0 0 10px var(--slingsip-glow-primary); }.next time { color: var(--mint); }.slot-copy { min-width: 0; }.slot-copy strong { font-size: 12px; font-weight: 500; }.slot-copy p { font-size: 10px; margin: 5px 0 0; }.timeline-slot > .pill { margin-left: auto; font-size: 9px; padding: 4px 7px; }.schedule-note { border-top: 1px solid var(--line); padding-top: 15px; margin: 4px 0 0; font-size: 10px; }@media (max-width: 700px) { .timeline-slot { gap: 13px; }.timeline-slot > .pill { display: none; }.time { min-width: 87px; gap: 10px; } }'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DailyScheduleComponent { readonly state = inject(OverviewState); }
