import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { OverviewState } from './overview-state.service';
import { UiIconComponent } from '../../shared/ui-icon.component';
@Component({
  selector: 'app-desktop-integration', imports: [UiIconComponent],
  template: `<section class="panel desktop-panel" aria-labelledby="desktop-heading"><div class="desktop-intro"><span class="icon-tile"><app-ui-icon name="desktop" /></span><div><h2 id="desktop-heading">At home on your desktop.</h2><p class="muted">A quiet companion, right when you need one.</p></div><span class="pill" [class.quiet]="!state.available()"><span class="status-dot" [class.inactive]="!state.available()"></span>{{ state.available() ? 'Connected' : 'Unavailable' }}</span></div><dl class="desktop-details"><div><dt>Companion</dt><dd data-testid="companion-status">{{ !state.available() ? 'Unavailable' : state.desktop.overlayVisible() ? 'Visible' : state.snapshot()?.reminderRetry?.pending ? 'Waiting to return' : 'Resting offscreen' }}</dd></div><div><dt>Mouse input</dt><dd data-testid="mouse-mode">{{ state.snapshot()?.overlay?.interactive ? 'Interactive target' : state.inputLabel() }}</dd></div><div><dt>Next reminder</dt><dd>{{ state.nextBreak().value }}</dd></div><div><dt>Primary display</dt><dd>{{ state.displaySize() }}</dd></div></dl>
    @if (state.desktop.overlayVisible() || state.snapshot()?.reminderRetry?.pending) { <button class="secondary" type="button" data-testid="cancel-overlay" (click)="state.desktop.hideOverlay()" [disabled]="state.desktop.busy()">Hide reminder</button> }
  </section>`,
  styleUrl: './overview-card.scss', styles: ['.desktop-intro { display: flex; align-items: center; gap: 13px; flex-wrap: wrap; }.desktop-intro h2 { margin: 0 0 5px; }.desktop-intro p { margin: 0; font-size: 11px; }.desktop-intro > .pill { margin-left: auto; }.desktop-details { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 20px; margin: 23px 0 0; padding-top: 18px; border-top: 1px solid var(--line); }.desktop-details > div { min-width: 0; }.desktop-details dt { font-size: 10px; color: var(--muted); margin-bottom: 7px; }.desktop-details dd { margin: 0; font-size: 11px; color: var(--text); line-height: 1.5; }.desktop-panel > button { margin-top: 18px; }@media (max-width: 1250px) { .desktop-details { grid-template-columns: repeat(2, minmax(0, 1fr)); } }@media (max-width: 700px) { .desktop-intro h2 { font-size: 15px; }.desktop-intro > .pill { margin-left: 48px; }.desktop-details { grid-template-columns: 1fr; gap: 15px; } }'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DesktopIntegrationComponent { readonly state = inject(OverviewState); }
